#
# Part of RedELK
# Docker compose config for RedELK
#
# Author: Outflank B.V. / Marc Smeets
#
#

version: "3.3"

networks:
  dockernetredelk:
    driver: bridge

volumes:
  redelk_es_data:
    driver: local
  redelk_logstash_data:
    driver: local
  redelk_kibana_data:
    driver: local
  redelk_jupyter_data:
    driver: local
  redelk_bloodhound_data:
    driver: local

services:
  elasticsearch:
    container_name: redelk-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    networks:
      - dockernetredelk
    expose:
      - "9200"
    volumes:
      - redelk_es_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - cluster.name=redelk-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      #- xpack.security.enabled=false
      #- xpack.watcher.enabled=false
      - COMPOSE_PROJECT_NAME=redelk
      - CERTS_DIR=/usr/share/elasticsearch/config/certificates
      - CERTS_DIR_KBN=/usr/share/kibana/config/certificates
      - CERTS_DIR_LOGSTASH=/usr/share/logstash/config/certificates
      - ELASTIC_PASSWORD=redelk
      - CREDS_kibana_system=GxIOh5OQ26sLJ4XzBPIEnWjGJPrTDT2A
      - CREDS_logstash_system=Q0AZ9ZH0yVk6chGC-ElSxE0U5zh9_RPd
      - CREDS_redelk_ingest=XF461F5CXlJZmsCeiBOyQDSQ4j2Ro6t1
      - ES_URL=https://redelk-elasticsearch:9200
    restart: always

  logstash:
    container_name: redelk-logstash
    build: ./redelk-logstash
    networks:
      - dockernetredelk
    ports:
      - "5044:5044"
    expose:
      - "9600"
    volumes:
      - ./redelk-logstash/live/certs:/usr/share/logstash/redelk-main/certs
      - ./redelk-base/live/redelklogs:/var/log/redelk
    environment:
      - node.name=redelk-logstash
      - config.reload.automatic:true
    restart: always
    depends_on:
      - elasticsearch

  kibana:
    container_name: redelk-kibana
    build: ./redelk-kibana
    networks:
      - dockernetredelk
    expose:
      - "5601"
    volumes:
      - redelk_kibana_data:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_URL=http://redelk-elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://redelk-elasticsearch:9200
      #- xpack.security.enabled=false
    restart: always
    depends_on:
      - logstash

  nginx:
    container_name: redelk-nginx
    image: nginx:latest
    networks:
      - dockernetredelk
    volumes:
      - ./redelk-nginx/live/config:/etc/nginx/conf.d
      - ./redelk-base/live/var_www_html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - kibana

  base:
    container_name: redelk-base
    build: ./redelk-base
    networks:
      - dockernetredelk
    volumes:
      - ./redelk-base/live/var_www_html:/var/www/html
      - ./redelk-base/live/config/etc/cron.d:/etc/cron.d
      - ./redelk-base/live/config/etc/redelk:/etc/redelk
      - ./redelk-base/live/redelklogs:/var/log/redelk
      - ./redelk-base/live/ssh:/home/redelk/.ssh
    restart: always
    depends_on:
      - nginx

  jupyter:
    container_name: redelk-jupyter
    build: ./redelk-jupyter
    networks:
      - dockernetredelk
    expose:
      - "8888"
    volumes:
      - ./redelk-jupyter/live/workbooks:/home/jovyan/work
    restart: always
    depends_on:
      - base

  bloodhound:
    container_name: redelk-bloodhound
    image: specterops/bloodhound-neo4j
    networks:
      - dockernetredelk
    volumes:
      - redelk_bloodhound_data:/var/lib/neo4j
    ports:
      - "7687:7687"
    expose: 
      - "7474"
    environment:
      - NEO4J_AUTH=neo4j/BloodHound
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_memory_pagecache_size=1G
    depends_on:
      - jupyter