name: Pylint

on:
  push:
    paths:
      - 'elkserver/docker/redelk-base/redelkinstalldata/scripts'
  # pull_request_target:
  #   paths:
  #     - 'elkserver/docker/redelk-base/redelkinstalldata/scripts'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        apt-get install python3-pil
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r elkserver/docker/redelk-base/redelkinstalldata/scripts/requirements.txt
    - name: Analysing the code with pylint
      run: |
        PYLINTRC=$(pwd)/elkserver/docker/redelk-base/redelkinstalldata/scripts/.pylintrc find elkserver/docker/redelk-base/redelkinstalldata/scripts -name '*.py' -exec echo pylint {} \; -exec pylint {} \;

